// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FeatureBlock: typeof import('./components/FeatureBlock.vue')['default']
    FeatureCard: typeof import('./components/FeatureCard.vue')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    IconCustomTextLogo: typeof import('~icons/custom/text-logo')['default']
    IconFluentAccessibility24Filled: typeof import('~icons/fluent/accessibility24-filled')['default']
    IconFluentChevronDoubleDown16Regular: typeof import('~icons/fluent/chevron-double-down16-regular')['default']
    InlineDynamicText: typeof import('./components/InlineDynamicText.vue')['default']
    LanguageSwitch: typeof import('./components/LanguageSwitch.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
  }
}

export { }
